# Generated by Django 5.0.1 on 2024-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_time', '0002_rename_storetype_shop_shop_type_alter_shop_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tags',
            field=models.ManyToManyField(to='misc_time.tag'),
        ),
    ]
